/**
 * `penv init` — scaffold a project.
 *
 * Every step is idempotent, and two of them are write-once on purpose:
 * `.penv/env.ts` is yours the moment it exists (invariant 2 — penv scaffolds it,
 * never regenerates it), and `penv.config.ts` is the environment whitelist you
 * declared. Re-running init reports what it kept rather than overwriting it.
 */

import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { PenvError } from "@penv/core";
import { defineCommand } from "citty";
import { CHECK, formatSteps, guard, type Step, write } from "../ui.js";

export const SCHEMA_FILE = "env.ts";
export const CONFIG_FILE = "penv.config.ts";
export const TSCONFIG_FILE = "tsconfig.json";
export const GITIGNORE_FILE = ".gitignore";
export const PENV_DIR = ".penv";

const ALIAS = "@env";
const ALIAS_TARGET = ".penv/env.ts";

/** What init touched, so a caller can report it and a test can assert it. */
export type InitTarget = "penv-dir" | "schema" | "config" | "tsconfig" | "gitignore";
export type InitAction = "created" | "kept" | "updated";

export interface InitStep {
  readonly target: InitTarget;
  readonly action: InitAction;
  /** The reported line, in the docs' voice. */
  readonly text: string;
  readonly note?: string;
}

export interface InitResult {
  readonly root: string;
  readonly steps: readonly InitStep[];
}

export interface InitOptions {
  readonly cwd: string;
}

/*
 * Templates.
 */

/** One schema field for the draft `penv import` generates. */
export interface SchemaField {
  readonly key: string;
  /** The Zod expression, e.g. `z.url()`. */
  readonly type: string;
}

const EMPTY_SCHEMA_BODY =
  "  // One key per parameter, e.g. `databaseUrl: z.url(),`. Nesting a key nests\n" +
  "  // the parameter: `redis: z.object({ password: z.string() })` is redis/password.";

const DRAFT_HEADER =
  "// DRAFT — generated by `penv import` from one sample of each value, and yours\n" +
  "// to correct. Single-sample inference cannot know that a boolean seen as `true`\n" +
  "// must also accept `1`/`0`, or that a string is really a URL. penv scaffolds\n" +
  "// this file once and never regenerates it, so edits here are safe.\n";

export function renderSchemaModule(fields: readonly SchemaField[], draft: boolean): string {
  const body =
    fields.length === 0
      ? EMPTY_SCHEMA_BODY
      : fields.map((field) => `  ${field.key}: ${field.type},`).join("\n");

  return (
    `${draft ? DRAFT_HEADER : ""}import { z } from "zod";\n` +
    `import { load } from "penv";\n` +
    `\n` +
    `// The shape. Import this (or z.infer<typeof schema>) when you only need the\n` +
    `// type — tests, tooling — so you don't trigger config loading.\n` +
    `export const schema = z.object({\n${body}\n});\n` +
    `\n` +
    `// The loaded, validated values for the current environment. Import this in app\n` +
    `// code. Importing it loads configuration and throws (naming the parameter and\n` +
    `// environment) if anything required is missing or invalid.\n` +
    `export const env = load(schema);\n`
  );
}

const CONFIG_TEMPLATE = `import { defineConfig } from "penv";

export default defineConfig({
  // Environments are a whitelist. A filename segment is an environment only if
  // it is declared here — penv never infers one from a folder or a filename.
  environments: ["development", "staging", "production"],

  providers: {
    development: { type: "filesystem" },
    staging: { type: "filesystem" },
    production: { type: "filesystem" },
  },
});
`;

/**
 * Invariant 17: value files are never committed; structure, `env.ts`, meta, and
 * config are. The negated directory pattern keeps git descending into namespace
 * folders, which an excluded directory would otherwise hide entirely.
 */
const GITIGNORE_TEMPLATE = `# Written by penv. Value files hold configuration values and are never
# committed; only the structure, env.ts, meta, and config are.
*
!*/
!.gitignore
!${SCHEMA_FILE}
!*.json
`;

/*
 * The tsconfig.json edit.
 *
 * The alias is inserted into the user's own file, so the file is scanned rather
 * than parsed and re-emitted: reformatting someone's tsconfig — dropping its
 * comments, resorting its keys — to add one path is not a minimal edit.
 */

function skipTrivia(source: string, index: number): number {
  let i = index;
  for (;;) {
    const ch = source.charAt(i);
    if (ch === " " || ch === "\t" || ch === "\n" || ch === "\r") {
      i += 1;
      continue;
    }
    if (ch === "/" && source.charAt(i + 1) === "/") {
      const end = source.indexOf("\n", i);
      i = end === -1 ? source.length : end + 1;
      continue;
    }
    if (ch === "/" && source.charAt(i + 1) === "*") {
      const end = source.indexOf("*/", i + 2);
      i = end === -1 ? source.length : end + 2;
      continue;
    }
    return i;
  }
}

/** Index just past the closing quote of the string opening at `index`. */
function endOfString(source: string, index: number): number {
  let i = index + 1;
  while (i < source.length) {
    const ch = source.charAt(i);
    if (ch === "\\") {
      i += 2;
      continue;
    }
    if (ch === '"') {
      return i + 1;
    }
    i += 1;
  }
  return source.length;
}

/** Index just past the bracket matching the one at `index`. */
function endOfBracket(source: string, index: number): number {
  const open = source.charAt(index);
  const close = open === "{" ? "}" : "]";
  let depth = 0;
  let i = index;
  while (i < source.length) {
    const ch = source.charAt(i);
    if (ch === '"') {
      i = endOfString(source, i);
      continue;
    }
    if (ch === "/" && (source.charAt(i + 1) === "/" || source.charAt(i + 1) === "*")) {
      i = skipTrivia(source, i);
      continue;
    }
    if (ch === open) {
      depth += 1;
      i += 1;
      continue;
    }
    if (ch === close) {
      depth -= 1;
      i += 1;
      if (depth === 0) {
        return i;
      }
      continue;
    }
    i += 1;
  }
  return source.length;
}

function endOfValue(source: string, index: number): number {
  const ch = source.charAt(index);
  if (ch === '"') {
    return endOfString(source, index);
  }
  if (ch === "{" || ch === "[") {
    return endOfBracket(source, index);
  }
  let i = index;
  while (i < source.length) {
    const c = source.charAt(i);
    if (c === "," || c === "}" || c === "]" || c === "\n") {
      return i;
    }
    i += 1;
  }
  return source.length;
}

interface Member {
  readonly valueStart: number;
}

/** The member named `key` directly inside the object whose `{` is at `open`. */
function findMember(source: string, open: number, key: string): Member | undefined {
  const close = endOfBracket(source, open) - 1;
  let i = skipTrivia(source, open + 1);
  while (i < close) {
    if (source.charAt(i) !== '"') {
      return undefined;
    }
    const keyEnd = endOfString(source, i);
    const name = source.slice(i + 1, keyEnd - 1);
    const colon = skipTrivia(source, keyEnd);
    if (source.charAt(colon) !== ":") {
      return undefined;
    }
    const valueStart = skipTrivia(source, colon + 1);
    const valueEnd = endOfValue(source, valueStart);
    if (name === key) {
      return { valueStart };
    }
    let next = skipTrivia(source, valueEnd);
    if (source.charAt(next) === ",") {
      next = skipTrivia(source, next + 1);
    }
    i = next;
  }
  return undefined;
}

/** The indentation of the line `index` sits on. */
function lineIndent(source: string, index: number): string {
  const lineStart = source.lastIndexOf("\n", index) + 1;
  const match = /^[ \t]*/.exec(source.slice(lineStart, index));
  return match?.[0] ?? "";
}

/** The file's own indentation unit, so the inserted line looks like its neighbours. */
function indentUnit(source: string): string {
  const match = /\n([ \t]+)"/.exec(source);
  return match?.[1] ?? "  ";
}

function insertMember(source: string, open: number, member: string, unit: string): string {
  const objectIndent = lineIndent(source, open);
  const entryIndent = objectIndent + unit;
  const close = endOfBracket(source, open) - 1;
  if (skipTrivia(source, open + 1) === close) {
    return `${source.slice(0, open + 1)}\n${entryIndent}${member}\n${objectIndent}${source.slice(close)}`;
  }
  return `${source.slice(0, open + 1)}\n${entryIndent}${member},${source.slice(open + 1)}`;
}

function shapeError(what: string): PenvError {
  return new PenvError(
    "TSCONFIG_SHAPE",
    `penv cannot add the \`${ALIAS}\` path alias to tsconfig.json: ${what}`,
    `Add it by hand: \`{ "compilerOptions": { "paths": { "${ALIAS}": ["${ALIAS_TARGET}"] } } }\`.`,
  );
}

export interface AliasEdit {
  readonly source: string;
  readonly changed: boolean;
}

/**
 * `tsconfig.json` with the `@env` alias present, everything else untouched.
 * Already-aliased input comes back unchanged rather than gaining a duplicate.
 */
export function insertEnvAlias(source: string): AliasEdit {
  const alias = `"${ALIAS}": ["${ALIAS_TARGET}"]`;
  const root = skipTrivia(source, 0);
  if (source.charAt(root) !== "{") {
    throw shapeError("its contents are not a JSON object");
  }

  const unit = indentUnit(source);
  const compilerOptions = findMember(source, root, "compilerOptions");
  if (compilerOptions === undefined) {
    return {
      source: insertMember(source, root, `"compilerOptions": { "paths": { ${alias} } }`, unit),
      changed: true,
    };
  }
  if (source.charAt(compilerOptions.valueStart) !== "{") {
    throw shapeError("`compilerOptions` is not an object");
  }

  const paths = findMember(source, compilerOptions.valueStart, "paths");
  if (paths === undefined) {
    return {
      source: insertMember(source, compilerOptions.valueStart, `"paths": { ${alias} }`, unit),
      changed: true,
    };
  }
  if (source.charAt(paths.valueStart) !== "{") {
    throw shapeError("`compilerOptions.paths` is not an object");
  }

  if (findMember(source, paths.valueStart, ALIAS) !== undefined) {
    return { source, changed: false };
  }
  return { source: insertMember(source, paths.valueStart, alias, unit), changed: true };
}

const TSCONFIG_TEMPLATE = `{
  "compilerOptions": {
    "paths": { "${ALIAS}": ["${ALIAS_TARGET}"] }
  }
}
`;

/*
 * The steps themselves. Each returns what it did so the caller reports it.
 */

export function ensurePenvDir(root: string): InitStep {
  const dir = resolve(root, PENV_DIR);
  if (existsSync(dir)) {
    return { target: "penv-dir", action: "kept", text: `Found ${PENV_DIR}/` };
  }
  mkdirSync(dir, { recursive: true });
  return { target: "penv-dir", action: "created", text: `Created ${PENV_DIR}/` };
}

/**
 * Invariant 2: `.penv/env.ts` is scaffolded once and never regenerated. An
 * existing file is the user's, whatever penv would have written instead.
 */
export function writeSchemaFile(
  root: string,
  fields: readonly SchemaField[],
  draft: boolean,
): InitStep {
  const file = join(root, PENV_DIR, SCHEMA_FILE);
  if (existsSync(file)) {
    return {
      target: "schema",
      action: "kept",
      text: `Kept ${ALIAS_TARGET}`,
      note: "(yours — penv never regenerates it)",
    };
  }
  mkdirSync(join(root, PENV_DIR), { recursive: true });
  writeFileSync(file, renderSchemaModule(fields, draft), "utf8");
  return {
    target: "schema",
    action: "created",
    text: `Generated ${ALIAS_TARGET}`,
    note: draft ? "(draft schema — review it, it's yours)" : "(schema + loader — yours to edit)",
  };
}

export function writeConfigFile(root: string): InitStep {
  const file = join(root, CONFIG_FILE);
  if (existsSync(file)) {
    return { target: "config", action: "kept", text: `Kept ${CONFIG_FILE}` };
  }
  writeFileSync(file, CONFIG_TEMPLATE, "utf8");
  return { target: "config", action: "created", text: `Generated ${CONFIG_FILE}` };
}

export function writeTsconfigAlias(root: string): InitStep {
  const file = join(root, TSCONFIG_FILE);
  if (!existsSync(file)) {
    writeFileSync(file, TSCONFIG_TEMPLATE, "utf8");
    return {
      target: "tsconfig",
      action: "created",
      text: `Created ${TSCONFIG_FILE} with the ${ALIAS} path alias`,
    };
  }
  const edit = insertEnvAlias(readFileSync(file, "utf8"));
  if (!edit.changed) {
    return {
      target: "tsconfig",
      action: "kept",
      text: `Kept the ${ALIAS} path alias in ${TSCONFIG_FILE}`,
    };
  }
  writeFileSync(file, edit.source, "utf8");
  return {
    target: "tsconfig",
    action: "updated",
    text: `Added ${ALIAS} path alias to ${TSCONFIG_FILE}`,
  };
}

/**
 * The ignore file lives inside `.penv/`, where the value files are: penv owns it
 * outright, so it is rewritten when it drifts. A weakened ignore file is how a
 * plaintext secret gets committed, which invariant 17 exists to prevent.
 */
export function writeGitignore(root: string): InitStep {
  const file = join(root, PENV_DIR, GITIGNORE_FILE);
  const relative = `${PENV_DIR}/${GITIGNORE_FILE}`;
  const existing = existsSync(file) ? readFileSync(file, "utf8") : undefined;
  if (existing === GITIGNORE_TEMPLATE) {
    return { target: "gitignore", action: "kept", text: `Kept ${relative}` };
  }
  mkdirSync(join(root, PENV_DIR), { recursive: true });
  writeFileSync(file, GITIGNORE_TEMPLATE, "utf8");
  return {
    target: "gitignore",
    action: existing === undefined ? "created" : "updated",
    text: `${existing === undefined ? "Created" : "Updated"} ${relative}`,
  };
}

/** Everything `init` scaffolds, in the order it is reported. */
export function scaffold(root: string, fields: readonly SchemaField[], draft: boolean): InitStep[] {
  return [
    ensurePenvDir(root),
    writeSchemaFile(root, fields, draft),
    writeConfigFile(root),
    writeTsconfigAlias(root),
    writeGitignore(root),
  ];
}

export function runInit(options: InitOptions): InitResult {
  const root = resolve(options.cwd);
  return { root, steps: scaffold(root, [], false) };
}

export function renderInit(result: InitResult): string[] {
  const steps: Step[] = result.steps.map((step) =>
    step.note === undefined
      ? { glyph: CHECK, text: step.text }
      : { glyph: CHECK, text: step.text, note: step.note },
  );
  return [
    ...formatSteps(steps),
    "",
    "Done. Declare your parameters in .penv/env.ts, then `penv set <key>`.",
  ];
}

export const initCommand = defineCommand({
  meta: { name: "init", description: "Initialize a project (.penv/, env.ts, config, @env alias)" },
  run() {
    return guard(async () => {
      write(renderInit(runInit({ cwd: process.cwd() })));
    });
  },
});
