/**
 * The committed snapshot — `penv.snapshot.ts` at the project root — that lets
 * `load()` resolve in a bundled or serverless runtime where no `penv.config.ts`
 * or `.penv/` tree is on disk. It embeds the evaluated config and every committed
 * sealed value; the scaffolded `env.ts` imports it and passes it to `load`.
 *
 * Sealed records only, by decision: the snapshot ships exactly what a git clone
 * already sees — ciphertext, safe to commit — and never plaintext, at any scope,
 * nor either `.local` scope. Determinism is the point of the text output: value
 * keys are code-unit sorted, so `doctor snapshot-stale` is a plain text compare
 * against a recomputed snapshot.
 *
 * It sits beside `penv.config.ts` and `penv.schema.ts`, outside `.penv/`, so the
 * value-file grammar walker never sees it (no `StrayCodeFileError`) and it is
 * committed by default — the same placement rationale as the schema shape.
 */

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import type { PenvConfig, PenvSnapshot, SyncValueSource } from "@penvhq/core";
import { schemaFileOf, sealedSnapshotValues, snapshotDigest } from "@penvhq/core";
import { createFilesystemProvider } from "@penvhq/provider-filesystem";
import { localTree, PENV_DIR, type Project } from "./project.js";

export const SNAPSHOT_FILE = "penv.snapshot.ts";

/**
 * Which values a snapshot embeds, and the digest binding it to them, both come
 * from core — the runtime recomputes the same digest to detect drift, and two
 * implementations of "the sealed inputs" would drift from each other first.
 */
function snapshotOf(config: PenvConfig, tree: SyncValueSource): PenvSnapshot {
  const values = sealedSnapshotValues(tree);
  return { v: 1, config, values, digest: snapshotDigest(config, values) };
}

/** The snapshot for a root and its evaluated config — the seam `init` builds from. */
export function buildSnapshotFrom(root: string, config: PenvConfig): PenvSnapshot {
  return snapshotOf(config, createFilesystemProvider({ root: join(root, PENV_DIR), config }));
}

/** Pure: the snapshot an open project's local tree and config imply. */
export function buildSnapshot(project: Project): PenvSnapshot {
  return snapshotOf(project.config, localTree(project));
}

/** The deterministic module text — a recompute of this is what drift-detects. */
export function renderSnapshotModule(snapshot: PenvSnapshot): string {
  const body = JSON.stringify(snapshot, null, 2);
  return (
    "// penv.snapshot.ts — GENERATED by penv. Do not edit; run `penv snapshot` to refresh.\n" +
    "// It embeds the evaluated config and every committed sealed (.enc) value, so `load()`\n" +
    "// resolves in a bundled or serverless runtime where no penv.config.ts is on disk.\n" +
    'import type { PenvSnapshot } from "@penvhq/penv";\n' +
    "\n" +
    `export const snapshot = ${body} satisfies PenvSnapshot;\n`
  );
}

export interface SnapshotWriteResult {
  readonly file: string;
  readonly action: "created" | "updated" | "unchanged";
}

/** CRLF-tolerant equality — git's autocrlf may rewrite a checkout's line endings. */
export function equalsIgnoringEol(a: string, b: string): boolean {
  return a.replace(/\r\n/g, "\n") === b.replace(/\r\n/g, "\n");
}

/**
 * Writes `penv.snapshot.ts`, creating it or rewriting it only when its content
 * changed — so a no-op mutation never dirties the working tree. `penv snapshot`
 * and `init` call this; a mutation reaches it through {@link refreshSnapshot}.
 */
export function writeSnapshotFile(project: Project): SnapshotWriteResult {
  const path = join(project.root, SNAPSHOT_FILE);
  const wanted = renderSnapshotModule(buildSnapshot(project));
  const existing = existsSync(path) ? readFileSync(path, "utf8") : undefined;
  if (existing !== undefined && equalsIgnoringEol(existing, wanted)) {
    return { file: SNAPSHOT_FILE, action: "unchanged" };
  }
  writeFileSync(path, wanted, "utf8");
  return { file: SNAPSHOT_FILE, action: existing === undefined ? "created" : "updated" };
}

/** What a recompute says about the committed snapshot. */
export type SnapshotStatus = "absent" | "stale" | "current";

/**
 * Recompute and compare, writing nothing — `writeSnapshotFile`'s question
 * without its answer. A build bakes the snapshot's values in, so a snapshot that
 * has fallen behind the tree is a deploy that serves values nobody set; CI needs
 * to be able to ask, and to fail.
 */
export function checkSnapshotFile(project: Project): { file: string; status: SnapshotStatus } {
  const path = join(project.root, SNAPSHOT_FILE);
  if (!existsSync(path)) {
    return { file: SNAPSHOT_FILE, status: "absent" };
  }
  const wanted = renderSnapshotModule(buildSnapshot(project));
  const existing = readFileSync(path, "utf8");
  return {
    file: SNAPSHOT_FILE,
    status: equalsIgnoringEol(existing, wanted) ? "current" : "stale",
  };
}

/** Whether the project commits a snapshot — the opt-in every mutation hook checks. */
export function snapshotExists(root: string): boolean {
  return existsSync(join(root, SNAPSHOT_FILE));
}

/**
 * Regenerates the snapshot after a mutation, but only for a project that already
 * commits one. The snapshot is opt-in: a mutation never conjures one for a
 * project that never asked for it — that is `penv snapshot`'s (or `init`'s) job.
 */
export function refreshSnapshot(project: Project): void {
  if (snapshotExists(project.root)) {
    writeSnapshotFile(project);
  }
}

/**
 * The specifier the wrapper imports the snapshot by, relative to wherever the
 * wrapper is kept. The snapshot is always at the project root, so this is the
 * climb up to it — the same shape `init`'s `shapeSpecifier` uses for the schema.
 */
export function snapshotSpecifier(schemaFile: string): string {
  const depth = schemaFile.split("/").length - 1;
  const climb = depth === 0 ? "./" : "../".repeat(depth);
  return `${climb}penv.snapshot.js`;
}

/** What {@link wireEnvModule} did — `manual` carries the exact lines to add by hand. */
export interface WireResult {
  readonly file: string;
  readonly action: "wired" | "kept" | "manual";
  /** The import line to add — printed on `manual`. */
  readonly importLine: string;
  /** How to add `snapshot` to the load options — printed on `manual`. */
  readonly loadHint: string;
}

/** Inserts the snapshot import after the schema import, or the `load` import, or first. */
function insertSnapshotImport(source: string, importLine: string): string {
  const afterSchema =
    /^import\s*\{\s*schema\s*\}\s*from\s*["'][^"']*penv\.schema\.js["'];?[ \t]*\r?\n/m;
  const schemaMatch = afterSchema.exec(source);
  if (schemaMatch !== null) {
    const index = schemaMatch.index + schemaMatch[0].length;
    return `${source.slice(0, index)}${importLine}\n${source.slice(index)}`;
  }
  const afterLoad = /^import\s*\{[^}]*\}\s*from\s*["']@penvhq\/penv["'];?[ \t]*\r?\n/m;
  const loadMatch = afterLoad.exec(source);
  if (loadMatch !== null) {
    const index = loadMatch.index + loadMatch[0].length;
    return `${source.slice(0, index)}${importLine}\n${source.slice(index)}`;
  }
  return `${importLine}\n${source}`;
}

/**
 * Additively wires `snapshot` into the scaffolded wrapper `env.ts`: the import,
 * and `snapshot` in the `load(schema, { … })` options. It recognises the shapes
 * penv itself writes — `load(schema)` and `load(schema, { … })` — and refuses to
 * guess at anything else, printing the two lines to add by hand instead (init's
 * ask-don't-guess philosophy). An already-wired module is left untouched.
 */
export function wireEnvModule(project: Project): WireResult {
  const schemaFile = schemaFileOf(project.config);
  const specifier = snapshotSpecifier(schemaFile);
  const importLine = `import { snapshot } from "${specifier}";`;
  const loadHint = "pass it to load: `load(schema, { snapshot })`";
  const manual: WireResult = { file: schemaFile, action: "manual", importLine, loadHint };

  const path = join(project.root, ...schemaFile.split("/"));
  if (!existsSync(path)) {
    return manual;
  }
  const source = readFileSync(path, "utf8");

  const loadCall = /load\(\s*schema\s*(\)|,\s*\{([\s\S]*?)\}\s*\))/;
  const match = loadCall.exec(source);
  if (match === null) {
    return manual;
  }

  const options = match[2];
  // A `snapshot` property (shorthand or keyed) — not the word appearing in a string.
  const snapshotProperty = /(?:^|[,{\s])snapshot\s*(?=[,:}]|$)/;
  const snapshotInOptions = options !== undefined && snapshotProperty.test(options);
  const importPresent = source.includes(importLine);
  if (snapshotInOptions && importPresent) {
    return { file: schemaFile, action: "kept", importLine, loadHint };
  }

  let updated = source;
  if (!snapshotInOptions) {
    // Multi-line options carry a trailing comma; strip it so appending never doubles it.
    const trimmed = (options ?? "").trim().replace(/,$/, "");
    const replacement =
      match[1] === ")" || trimmed.length === 0
        ? "load(schema, { snapshot })"
        : `load(schema, { ${trimmed}, snapshot })`;
    updated = updated.replace(loadCall, replacement);
  }
  if (!importPresent) {
    updated = insertSnapshotImport(updated, importLine);
  }
  if (updated === source) {
    return { file: schemaFile, action: "kept", importLine, loadHint };
  }
  writeFileSync(path, updated, "utf8");
  return { file: schemaFile, action: "wired", importLine, loadHint };
}
